---
title: "Laboratorium 9"
author: "Tutaj wpisz swoje dane"
date: "12/1/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Do zrobienia

Poniższe zadania oparte są o dane z pakietu `PogromcyDanych`

*  Na bazie danych `koty_ptaki` zbuduj wykres przedstawiający za pomocą punktów wiersze z tego zbioru danych. Na osi OX powinna znajdować się długość a na osi OY prędkość. Za pomocą kształtu i koloru punktów oznacz wartości z kolumny druzyna.
* Na bazie danych `koty_ptaki` zbuduj wykres przedstawiający dla gatunków długość oraz prędkość osobników. Na osi OX powinna znajdować się długość a na osi OY prędkość. Na wykresie w powinny znaleźć się nazwy gatunków we współrzędnych określonych przez ich długość i prędkość.
* Na bazie danych `koty_ptaki` zbuduj wykres przedstawiający dla gatunków długość oraz wagę osobników. Na osi OX powinna znajdować się długość a na osi OY waga. Na wykresie należy przedstawić przynajmniej dwie warstwy - dwie geometrie, jedną z punktami a drugą z nazwami gatunków.
* Na bazie danych `koty_ptaki` zbuduj wykres przedstawiający dla gatunków długość oraz prędkość osobników. Na osi OX powinna znajdować się długość a na osi OY prędkość. Do wykresu dodaj linię trendu używając geometrii smooth. Na wykresie należy przedstawić przynajmniej dwie warstwy - dwie geometrie, jedną z punktami a drugą z trendem.
*  W zbiorze danych `pearson` znajdują się informacje o wzroście ojca i syna. Wykorzystując ten zbiór danych zbuduj wykres, który na osi OX będzie przedstawiał wzrost ojca a na osi OY wzrost syna. Przedstaw poszczególne dane za pomocą punktów oraz dodaj linie trendu wyznaczoną przez geometrie `smooth`.
* W zbiorze danych `serialeIMDB` znajdują się informacje o ocenach odcinków 200 wybranych seriali. Wykorzystując ten zbiór danych zbuduj wykres, który na osi OY będzie przedstawiał nazwę serialu a na osi OX przedstawiony będzie rozkład ocen odcinków tego serialu za pomocą wykresu pudełko wąsy. Seriali jest ponad 200, więc aby wykres się wyświetlał musi być dużo miejsca w pionie.
* Zbuduj wykres zgodnie z powyższym zadaniem. Zatroszcz się też o to, by kolejność nazw seriali na wykresie odpowiadała medianom ocen. Tzn. serial o najniższej medianie ocen powinien być wyświetlony na dole a o najwyższej na górze osi OY. Aby uporządkować seriale należy wykorzystać funkcję `reorder()`.
* W zbiorze danych diagnoza znajdują się dwie ciekawe zmienne: `eduk4_2013` z poziomem edukacji respondenta wyrażonym w czteropoziomowej skali oraz `gp29` odpowiedź na pytanie co jest ważniejsze w życiu.
* Zbuduj wykres słupkowy (z użyciem geometrii bar), który na osi OX przedstawi słupki dla różnych wartości zmiennej eduk4_2013, każdy słupek zostanie podzielony na części wypełnione różnymi kolorami, odpowiadające udziałowi różnych odpowiedzi zmiennej `gp29`.
* Wykonaj wykres, tak jak opisano powyżej. Następnie zmodyfikuj go aby: legenda znajdowała się na górze wykresu, wykres posiadał tytuł ‘Co jest ważniejsze?’, osie OX i OY były zamienione ze sobą (na osi OY edukacja a na OX liczba).

