---
title: "Laboratorium 1"
author: "Tutaj wpisz swoje dane"
date: "06/10/2017"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Do zrobienia

1. Pobierz plik https://github.com/pbiecek/PISA2012lite/blob/master/data/student2012.rda
2. Wybierz ciekawą zmienną (patrz opis http://www.oecd.org/pisa/pisaproducts/PISA12_StQ_FORM_A_ENG.pdf)
3. Przygotuj raport w knitrze przedstawiający rozkład wybranej zmiennej dla różnych krajów
4. Umieść w raporcie wykres, tabelę, kod R, krótki opis z formatowaniem.

Ściągawka knitra i markdowna

https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf

```{r}
load("~/Downloads/student2012.rda")
```

```{r}
a<-prop.table(table(student2012$CNT, student2012$ST08Q01),2)
a
najwiecej<-order(a[,4], decreasing=TRUE)
a[najwiecej]
kraje<-unique(student2012$CNT)

kraje[najwiecej]



proporcje<-prop.table(table(student2012$CNT, student2012$ST08Q01), 1)
sort(proporcje[,1])


proporcje['Poland',]
proporcje['Germany',]

proporcje[c('Poland','Germany'),]

wyniki<-tapply(student2012$PV1MATH, student2012$CNT, mean)
sort(wyniki)

```



