---
title: "imi_native_piechart"
author: "Agnieszka Gajewska"
date: "23 października 2017"
output: 
 pdf_document:
    toc: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(magrittr)
library(dplyr)
library(sqldf)
library(scales)
library(ggrepel)
library(forcats)
library(scales)
```

## R Markdown



```{r, echo=FALSE}
load("C:/Users/Aga/Downloads/student2012.rda")
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
#pozwala znaleźć kraje występujące w danej ramce danych
find_countries<-function(dataframe,variable){

countries = unique(dataframe[variable])

countries<-countries[,1]

return(countries<-as.vector(countries))
}
```

```{r,echo=FALSE}
#Wybiera dane dla kraju który nas interesuje i zwraca tabelę procentową (stosunek imigrantów do lokalnych mieszkańców)
prepare_data<-function(name_of_the_country, dataframe, variable ){
  data_for_the_specific_country <- subset(dataframe, dataframe["CNT"] == name_of_the_country)
  
  data_for_the_specific_country<-data_for_the_specific_country[variable]
    data_for_the_specific_country<-na.omit(data_for_the_specific_country)
  
    percent_table=prop.table(table(data_for_the_specific_country[variable]))
    
    
   percent_table<-as.data.frame(percent_table)
    colnames(percent_table)<-c("Country_of_origin", "Percentage")
    return(percent_table)
}
```

```{r,echo=FALSE}
#zwraca piechart immigrants-natives 
show_immigrants_natives_ratio<-function(name_of_the_country, dataframe, variable){
  
    percent_table<-prepare_data(name_of_the_country,dataframe, variable)
    
   percent_table<-percent_table %>%
arrange(desc(Percentage))%>%
     mutate(per = round(Percentage*100, digits=2))

print(pie <- ggplot(percent_table, aes(x = "", y = Percentage, fill = fct_inorder(Country_of_origin))) +
       geom_bar(width = 1, stat = "identity") +
       coord_polar("y", start = 0) +
       geom_label_repel(aes(label = per), size=5, show.legend = F, nudge_x = 1, box.padding = 0.25, label.padding = 0.25) +
       guides(fill = guide_legend(title = "Country of origin")))
    
}
```

```{r,echo=FALSE}

create_report<-function(dataframe){
 vector_of_countries<-find_countries(dataframe, 'CNT')
  for (country in vector_of_countries){

  
    
    show_immigrants_natives_ratio(country, student2012, 'ST20Q01')
    

  }
  
}

create_report(student2012)
```

