---
title: "Gaj_Mac_Szym"
author: "Agnieszka Gajewska"
date: "20 października 2017"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
setup_dependencies <- function(){
  if (!require(devtools)) {
    install.packages("devtools")
    require(devtools)
  }
  if (!require(ggplot2)) {
    install.packages("ggplot2")
    require(ggplot2)
  }
  if (!require(magrittr)) {
    install.packages("magrittr")
    require(magrittr)
  }
  if (!require(dplyr)) {
    install.packages("dplyr")
    require(dplyr)
  }
  if (!require(sqldf)) {
    install.packages("sqldf")
    require(sqldf)
  }
  if (!require(devtools)) {
    install.packages("devtools")
    require(devtools)
  }
  if (!require("PISA2012lite")) {
    devtools::install_github("pbiecek/PISA2012lite")
    library("PISA2012lite")
  }
  student2012 <- PISA2012lite::student2012
}

plot_results_foreigners_vs_locals <- function(country, data, args){
data %>%
  filter(data[args[['countries']]]==country) %>%
  select(args[['foreigner']],"PV1MATH") %>%
  na.omit(.) %>%
  group_by(ST20Q01) %>%
  summarise(meResult=mean(PV1MATH),n=n()) -> results

q <- ggplot(data=results,aes(x=ST20Q01,y=meResult)) + geom_bar(stat="identity",width=0.5,fill="steelblue") + 
geom_text(aes(label=round(meResult,digits=1)), vjust=1.6, color="white", size=4) +
labs(title="Math results by country of birth", xlab='Country of birth')
print(q)
}

transform_question_names <- function(curr_name, args){
  args[['proper_names']][match(curr_name, args[['reasons']])]
}

prep_df <-function(data)  { 
  temp <- data.frame(names = as.character("a"), variable = 0, value = 0)
  temp$names <- c("b")
  for(col in names(data)){
    tbl <- table(data[col])
    i <- 0
    for(lev in names(tbl)){
      i <- i + 1
      temp <- rbind(temp, c(as.character(col), i, tbl[lev]))
    }
  }
  temp <- temp[-1,]
  temp[,2] <- as.integer(temp[,2])
  temp[,3] <- as.integer(temp[,3])
  temp2 <- temp
  
  for(i in 1:dim(temp)[1]){
    row <- temp[i,]
    name <- row$names
    sum_for_name <- sum(temp[temp$names==name,]$value)
    temp2[i,3] <- temp[i,3]/sum_for_name
  }
  temp2$names <- sapply(temp2$names,transform_question_names, args)
  temp2$names <- as.factor(temp2$names)
  
  temp2
}

display_element_reasons <- function(country, data, args){
  data <- data[data[args[["countries"]]] == country,]
  foreigners <- data[data[args[["foreigner"]]] == args[['foreigner_opt']],]
  locals <- data[data[args[["foreigner"]]] == args[['local_opt']],]
  foreigners <- foreigners[args[['reasons']]]
  locals <- locals[args[['reasons']]]
  remove(data)
  
  locs <- prep_df(locals)
  foreigns <- prep_df(foreigners)
  locs$where_from = args[["local_opt"]]
  foreigns$where_from = args[["foreigner_opt"]]
  temp <- rbind(locs,foreigns)
  
  temp$where_from <- as.factor(temp$where_from)
  temp$variable <- as.factor(temp$variable)
  

  q <- ggplot(temp, aes(x = where_from, y = value),guide=FALSE) + facet_wrap(~names) + geom_bar(aes(fill = variable), position = "dodge", stat="identity") + guides(fill=FALSE, variable=FALSE)
  print(q)
}

print_page = function(country, data, args){
plot_results_foreigners_vs_locals(country,data,args)
display_element_reasons(country,data,args)
cat("abcd\n\\clearpage\n")
}

```


```{r, results="asis"}
setup_dependencies()
args <- list()
args['countries'] <- "CNT"
args[['reasons']] <- c("ST13Q01", "ST08Q01")
args[['proper_names']] <- c("prop_name1", "prop_name2")
args['foreigner'] <- "ST20Q01"
args[['foreigner_opt']] <- "Other country"
args[['local_opt']] <- "Country of test" # Assert it

countries = unique(student2012[args[['countries']]])[,1]
countries<-sort(as.vector(countries))


for(country in countries){
  print_page(country, student2012, args)
}

```

