---
title: "Malgorzata Pawlak - raport PISA 1/1"
output: pdf_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Context

[A new working paper](https://hbswk.hbs.edu/item/kids-benefit-from-having-a-working-mom) by Kathleen McGinn and her colleagues for Harvard Business School purports that working mothers are more likely to raise successful daughters.

# Preparing data

```{r data, message=FALSE, warning=FALSE}

# Loading data frame and libraries
load("/Users/Gosia/Documents/UNI/wizualizacja w R/student2012.rmd")
library(dplyr)
library(tidyr)

# Creating data frames with desired subsets of data and removing N/As
girls_gender <- student2012$ST04Q01 == "Female"
girls <- student2012[girls_gender, ]

girls_career <- na.omit(girls[,c("CNT", "ST15Q01","ST29Q05")])
girls_confidence <- na.omit(girls[,c("CNT","ST15Q01","ST43Q01")])

# Creating vector with a list of countries
countries_all <- unique(girls$CNT)

```

# Plots

"Learning mathematics is worthwhile for me because it will improve my career"

```{r,message=FALSE, warning=FALSE}

plot_career<-function(country) {
   with(girls_career[girls_career$CNT==country,], plot(ST15Q01,ST29Q05, main=country, las=2, col=rainbow(4), xlab="mother's working situation", ylab="math helping career prospects"))
 }

lapply(countries_all, plot_career)

```

```{r}


plot(girls_career$ST15Q01, girls_career$ST29Q05, par(las=2), xlab="mother's working situation", ylab="math helping career prospects")

```
